spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3307/booksystem?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: booksystem
  redis:
    port: 6379
    hostname: 52.80.116.14
    password: foobared
    timeout: 30000
    ssl: false